// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build nrf52840

// Package uarte provides access to the registers of the UARTE0 peripheral.
//
// Instances:
//  UARTE0  UARTE0_BASE  -  UARTE0_UART0*  UART with EasyDMA 0
//  UARTE1  UARTE1_BASE  -  UARTE1         UART with EasyDMA 1
// Registers:
//  0x000 32  TASK_STARTRX     Start UART receiver
//  0x004 32  TASK_STOPRX      Stop UART receiver
//  0x008 32  TASK_STARTTX     Start UART transmitter
//  0x00C 32  TASK_STOPTX      Stop UART transmitter
//  0x02C 32  TASK_FLUSHRX     Flush RX FIFO into RX buffer
//  0x100 32  EVENT_CTS        CTS is activated (set low). Clear To Send.
//  0x104 32  EVENT_NCTS       CTS is deactivated (set high). Not Clear To Send.
//  0x108 32  EVENT_RXDRDY     Data received in RXD (but potentially not yet transferred to Data RAM)
//  0x110 32  EVENT_ENDRX      Receive buffer is filled up
//  0x11C 32  EVENT_TXDRDY     Data sent from TXD
//  0x120 32  EVENT_ENDTX      Last TX byte transmitted
//  0x124 32  EVENT_ERROR      Error detected
//  0x144 32  EVENT_RXTO       Receiver timeout
//  0x14C 32  EVENT_RXSTARTED  UART receiver has started
//  0x150 32  EVENT_TXSTARTED  UART transmitter has started
//  0x158 32  EVENT_TXSTOPPED  Transmitter stopped
//  0x200 32  SHORTS           Shortcuts between local events and tasks
//  0x300 32  INTEN            Enable or disable interrupt
//  0x304 32  INTENSET         Enable interrupt
//  0x308 32  INTENCLR         Disable interrupt
//  0x480 32  ERRORSRC         Error source Note : this register is read / write one to clear.
//  0x500 32  ENABLE           Enable UART
//  0x508 32  PSEL_RTS         Pin select for RTS signal
//  0x50C 32  PSEL_TXD         Pin select for TXD signal
//  0x510 32  PSEL_CTS         Pin select for CTS signal
//  0x514 32  PSEL_RXD         Pin select for RXD signal
//  0x524 32  BAUDRATE         Baud rate. Accuracy depends on the HFCLK source selected.
//  0x534 32  RXD_PTR          Data pointer
//  0x538 32  RXD_MAXCNT       Maximum number of bytes in receive buffer
//  0x53C 32  RXD_AMOUNT       Number of bytes transferred in the last transaction
//  0x544 32  TXD_PTR          Data pointer
//  0x548 32  TXD_MAXCNT       Maximum number of bytes in transmit buffer
//  0x54C 32  TXD_AMOUNT       Number of bytes transferred in the last transaction
//  0x56C 32  CONFIG           Configuration of parity and hardware flow control
// Import:
//  github.com/embeddedgo/nrf5/p/mmap
package uarte

const (
	ENDRX_STARTRX SHORTS = 0x01 << 5 //+ Shortcut between event ENDRX and task STARTRX
	ENDRX_STOPRX  SHORTS = 0x01 << 6 //+ Shortcut between event ENDRX and task STOPRX
)

const (
	ENDRX_STARTRXn = 5
	ENDRX_STOPRXn  = 6
)

const (
	EOVERRUN ERRORSRC = 0x01 << 0 //+ Overrun error
	EPARITY  ERRORSRC = 0x01 << 1 //+ Parity error
	EFRAMING ERRORSRC = 0x01 << 2 //+ Framing error occurred
	EBREAK   ERRORSRC = 0x01 << 3 //+ Break condition
)

const (
	EOVERRUNn = 0
	EPARITYn  = 1
	EFRAMINGn = 2
	EBREAKn   = 3
)

const (
	EN       ENABLE = 0x0F << 0 //+ Enable or disable UARTE
	Disabled ENABLE = 0x00 << 0 //  Disable UARTE
	Enabled  ENABLE = 0x08 << 0 //  Enable UARTE
)

const (
	ENn = 0
)

const (
	BR         BAUDRATE = 0xFFFFFFFF << 0 //+ Baud rate
	Baud1200   BAUDRATE = 0x4F000 << 0    //  1200 baud (actual rate: 1205)
	Baud2400   BAUDRATE = 0x9D000 << 0    //  2400 baud (actual rate: 2396)
	Baud4800   BAUDRATE = 0x13B000 << 0   //  4800 baud (actual rate: 4808)
	Baud9600   BAUDRATE = 0x275000 << 0   //  9600 baud (actual rate: 9598)
	Baud14400  BAUDRATE = 0x3AF000 << 0   //  14400 baud (actual rate: 14401)
	Baud19200  BAUDRATE = 0x4EA000 << 0   //  19200 baud (actual rate: 19208)
	Baud28800  BAUDRATE = 0x75C000 << 0   //  28800 baud (actual rate: 28777)
	Baud31250  BAUDRATE = 0x800000 << 0   //  31250 baud
	Baud38400  BAUDRATE = 0x9D0000 << 0   //  38400 baud (actual rate: 38369)
	Baud56000  BAUDRATE = 0xE50000 << 0   //  56000 baud (actual rate: 55944)
	Baud57600  BAUDRATE = 0xEB0000 << 0   //  57600 baud (actual rate: 57554)
	Baud76800  BAUDRATE = 0x13A9000 << 0  //  76800 baud (actual rate: 76923)
	Baud115200 BAUDRATE = 0x1D60000 << 0  //  115200 baud (actual rate: 115108)
	Baud230400 BAUDRATE = 0x3B00000 << 0  //  230400 baud (actual rate: 231884)
	Baud250000 BAUDRATE = 0x4000000 << 0  //  250000 baud
	Baud460800 BAUDRATE = 0x7400000 << 0  //  460800 baud (actual rate: 457143)
	Baud921600 BAUDRATE = 0xF000000 << 0  //  921600 baud (actual rate: 941176)
	Baud1M     BAUDRATE = 0x10000000 << 0 //  1Mega baud
)

const (
	BRn = 0
)

const (
	HWFC     CONFIG = 0x01 << 0 //+ Hardware flow control
	PARITY   CONFIG = 0x07 << 1 //+ Parity
	Excluded CONFIG = 0x00 << 1 //  Exclude parity bit
	Included CONFIG = 0x07 << 1 //  Include even parity bit
	STOP     CONFIG = 0x01 << 4 //+ Stop bits
)

const (
	HWFCn   = 0
	PARITYn = 1
	STOPn   = 4
)
