// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build nrf52840

// Package spi provides access to the registers of the SPI0 peripheral.
//
// Instances:
//  SPI0  SPI0_BASE  -  SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0*  Serial Peripheral Interface 0
//  SPI1  SPI1_BASE  -  SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1*  Serial Peripheral Interface 1
//  SPI2  SPI2_BASE  -  SPIM2_SPIS2_SPI2*                   Serial Peripheral Interface 2
// Registers:
//  0x108 32  EVENT_READY  TXD byte sent and RXD byte received
//  0x304 32  INTENSET     Enable interrupt
//  0x308 32  INTENCLR     Disable interrupt
//  0x500 32  ENABLE       Enable SPI
//  0x508 32  PSEL_SCK     Pin select for SCK
//  0x50C 32  PSEL_MOSI    Pin select for MOSI signal
//  0x510 32  PSEL_MISO    Pin select for MISO signal
//  0x518 32  RXD          RXD register
//  0x51C 32  TXD          TXD register
//  0x524 32  FREQUENCY    SPI frequency. Accuracy depends on the HFCLK source selected.
//  0x554 32  CONFIG       Configuration register
// Import:
//  github.com/embeddedgo/nrf5/p/mmap
package spi

const (
	EN       ENABLE = 0x0F << 0 //+ Enable or disable SPI
	Disabled ENABLE = 0x00 << 0 //  Disable SPI
	Enabled  ENABLE = 0x01 << 0 //  Enable SPI
)

const (
	ENn = 0
)

const (
	FREQ FREQUENCY = 0xFFFFFFFF << 0 //+ SPI master data rate
	K125 FREQUENCY = 0x2000000 << 0  //  125 kbps
	K250 FREQUENCY = 0x4000000 << 0  //  250 kbps
	K500 FREQUENCY = 0x8000000 << 0  //  500 kbps
	M1   FREQUENCY = 0x10000000 << 0 //  1 Mbps
	M2   FREQUENCY = 0x20000000 << 0 //  2 Mbps
	M4   FREQUENCY = 0x40000000 << 0 //  4 Mbps
	M8   FREQUENCY = 0x80000000 << 0 //  8 Mbps
)

const (
	FREQn = 0
)

const (
	ORDER CONFIG = 0x01 << 0 //+ Bit order
	CPHA  CONFIG = 0x01 << 1 //+ Serial clock (SCK) phase
	CPOL  CONFIG = 0x01 << 2 //+ Serial clock (SCK) polarity
)

const (
	ORDERn = 0
	CPHAn  = 1
	CPOLn  = 2
)
