// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

//go:build nrf52840

// Package nvmc provides access to the registers of the NVMC peripheral.
//
// Instances:
//
//	NVMC  NVMC_BASE  -  -  Non Volatile Memory Controller
//
// Registers:
//
//	0x400 32  READY                Ready flag
//	0x408 32  READYNEXT            Ready flag
//	0x504 32  CONFIG               Configuration register
//	0x508 32  ERASEPAGE            Register for erasing a page in code area
//	0x50C 32  ERASEALL             Register for erasing all non-volatile user memory
//	0x510 32  ERASEPCR0            Deprecated register - Register for erasing a page in code area. Equivalent to ERASEPAGE.
//	0x514 32  ERASEUICR            Register for erasing user information configuration registers
//	0x518 32  ERASEPAGEPARTIAL     Register for partial erase of a page in code area
//	0x51C 32  ERASEPAGEPARTIALCFG  Register for partial erase configuration
//	0x540 32  ICACHECNF            I-code cache configuration register.
//	0x548 32  IHIT                 I-code cache hit counter.
//	0x54C 32  IMISS                I-code cache miss counter.
//
// Import:
//
//	github.com/embeddedgo/nrf5/p/mmap
package nvmc

const (
	WEN CONFIG = 0x03 << 0 //+ Program memory access mode. It is strongly recommended to only activate erase and write modes when they are actively used. Enabling write or erase will invalidate the cache and keep it invalidated.
	Ren CONFIG = 0x00 << 0 //  Read only access
	Wen CONFIG = 0x01 << 0 //  Write enabled
	Een CONFIG = 0x02 << 0 //  Erase enabled
)

const (
	WENn = 0
)

const (
	DURATION ERASEPAGEPARTIALCFG = 0x7F << 0 //+ Duration of the partial erase in milliseconds
)

const (
	DURATIONn = 0
)

const (
	CACHEEN     ICACHECNF = 0x01 << 0 //+ Cache enable
	CACHEPROFEN ICACHECNF = 0x01 << 8 //+ Cache profiling enable
)

const (
	CACHEENn     = 0
	CACHEPROFENn = 8
)
