// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build nrf52840

// Package irq provides the list of supported external interrupts.
package irq

const (
	POWER_CLOCK                       = 0
	RADIO                             = 1
	UARTE0_UART0                      = 2
	SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0 = 3
	SPIM1_SPIS1_TWIM1_TWIS1_SPI1_TWI1 = 4
	NFCT                              = 5
	GPIOTE                            = 6
	SAADC                             = 7
	TIMER0                            = 8
	TIMER1                            = 9
	TIMER2                            = 10
	RTC0                              = 11
	TEMP                              = 12
	RNG                               = 13
	ECB                               = 14
	CCM_AAR                           = 15
	WDT                               = 16
	RTC1                              = 17
	QDEC                              = 18
	COMP_LPCOMP                       = 19
	SWI0_EGU0                         = 20
	SWI1_EGU1                         = 21
	SWI2_EGU2                         = 22
	SWI3_EGU3                         = 23
	SWI4_EGU4                         = 24
	SWI5_EGU5                         = 25
	TIMER3                            = 26
	TIMER4                            = 27
	PWM0                              = 28
	PDM                               = 29
	MWU                               = 32
	PWM1                              = 33
	PWM2                              = 34
	SPIM2_SPIS2_SPI2                  = 35
	RTC2                              = 36
	I2S                               = 37
	FPU                               = 38
	USBD                              = 39
	UARTE1                            = 40
	QSPI                              = 41
	CRYPTOCELL                        = 42
	PWM3                              = 45
	SPIM3                             = 47
)
