// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build nrf52840

// Package gpio provides access to the registers of the P0 peripheral.
//
// Instances:
//  P0  P0_BASE  -  -  GPIO Port 1
//  P1  P1_BASE  -  -  GPIO Port 2
// Registers:
//  0x504 32  OUT          Write GPIO port
//  0x508 32  OUTSET       Set individual bits in GPIO port
//  0x50C 32  OUTCLR       Clear individual bits in GPIO port
//  0x510 32  IN           Read GPIO port
//  0x514 32  DIR          Direction of GPIO pins
//  0x518 32  DIRSET       DIR set register
//  0x51C 32  DIRCLR       DIR clear register
//  0x520 32  LATCH        Latch register indicating what GPIO pins that have met the criteria set in the PIN_CNF[n].SENSE registers
//  0x524 32  DETECTMODE   Select between default DETECT signal behaviour and LDETECT mode
//  0x700 32  PIN_CNF[32]  Description collection: Configuration of GPIO pins
// Import:
//  github.com/embeddedgo/nrf5/p/mmap
package gpio

const (
	DETECT DETECTMODE = 0x01 << 0 //+ Select between default DETECT signal behaviour and LDETECT mode
)

const (
	DETECTn = 0
)

const (
	DIRECTION PIN_CNF = 0x01 << 0  //+ Pin direction. Same physical register as DIR register
	INPUT     PIN_CNF = 0x01 << 1  //+ Connect or disconnect input buffer
	PULL      PIN_CNF = 0x03 << 2  //+ Pull configuration
	NoPull    PIN_CNF = 0x00 << 2  //  No pull
	Pulldown  PIN_CNF = 0x01 << 2  //  Pull down on pin
	Pullup    PIN_CNF = 0x03 << 2  //  Pull up on pin
	DRIVE     PIN_CNF = 0x07 << 8  //+ Drive configuration
	S0S1      PIN_CNF = 0x00 << 8  //  Standard '0', standard '1'
	H0S1      PIN_CNF = 0x01 << 8  //  High drive '0', standard '1'
	S0H1      PIN_CNF = 0x02 << 8  //  Standard '0', high drive '1'
	H0H1      PIN_CNF = 0x03 << 8  //  High drive '0', high 'drive '1''
	D0S1      PIN_CNF = 0x04 << 8  //  Disconnect '0' standard '1' (normally used for wired-or connections)
	D0H1      PIN_CNF = 0x05 << 8  //  Disconnect '0', high drive '1' (normally used for wired-or connections)
	S0D1      PIN_CNF = 0x06 << 8  //  Standard '0'. disconnect '1' (normally used for wired-and connections)
	H0D1      PIN_CNF = 0x07 << 8  //  High drive '0', disconnect '1' (normally used for wired-and connections)
	SENSE     PIN_CNF = 0x03 << 16 //+ Pin sensing mechanism
	Disabled  PIN_CNF = 0x00 << 16 //  Disabled
	High      PIN_CNF = 0x02 << 16 //  Sense for high level
	Low       PIN_CNF = 0x03 << 16 //  Sense for low level
)

const (
	DIRECTIONn = 0
	INPUTn     = 1
	PULLn      = 2
	DRIVEn     = 8
	SENSEn     = 16
)
