// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

// +build nrf52

// Package ppi provides access to the registers of the PPI peripheral.
//
// Instances:
//  PPI  PPI_BASE  -  -  Programmable Peripheral Interconnect
// Registers:
//  0x000 32  EN       Description cluster: Enable channel group n
//  0x004 32  DIS      Description cluster: Disable channel group n
//  0x510 32  EEP      Description cluster: Channel n event end-point
//  0x514 32  TEP      Description cluster: Channel n task end-point
//  0x910 32  TEP      Description cluster: Channel n task end-point
//  0x500 32  CHEN     Channel enable register
//  0x504 32  CHENSET  Channel enable set register
//  0x508 32  CHENCLR  Channel enable clear register
//  0x800 32  CHG[6]   Description collection: Channel group n
// Import:
//  github.com/embeddedgo/nrf5/p/mmap
package ppi

const (
	EN EN = 0x01 << 0 //+ Enable channel group n
)

const (
	ENn = 0
